name: ⏱️ Update README daily

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run update script
        run: python update.py

      - name: Commit changes
        run: |
          git config --global user.name 'perzy-codes'
          git config --global user.email 'pdabas@umd.edu'
          git add README.md
          git commit -m "🔄 Daily update" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
